config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'home#index'

  get 'home/index'
  get 'users/dashboard'
  get 'accounts', to: 'users#accounts'
  get 'wallets', to: 'users#wallets'

  patch 'verify/:payment_id', to: 'payments#verify', as: 'verify_payment'
  get '/payment_history', to: 'payments#history', as: 'payment_history'
  # post '/create_assurance_payment', to: 'payments#create_assurance_payment', as: 'create_assurance_payment'
  resources :pay_ins, only: [:create] do
    get :show_growth, on: :collection
  end
  resources :pay_outs, only: [:create]
  resources :users, only: [:index]
  namespace :support do
    resources :tickets, only: [:new, :create]
  end
end

app/views/shared/_assurance_payment_modal.html.erb
<div class="modal show" id="assurancePaymentModal-<%=payment.id%>" tabindex="-1" aria-labelledby="assurancePaymentModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="assurancePaymentModalLabel">Assurance Payment</h5>
      </div>
      <div class="modal-body">
        To wallet: <span id='assuranaceAmtwalletNumberToCopy'><%= payment.receiver_wallet_number.strip %></span>
        <span class="clipboard-btn btn btn-sm btn-primary" data-clipboard-action="copy" data-clipboard-target="#assuranaceAmtwalletNumberToCopy">copy</span>
        <p>Assurance Amount: <%= payment.amount %></p>
      </div>

      <%= render partial: 'shared/payment_verification_form', locals: {payment: payment} %>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center text-white mb-0">
  <!-- Copyright -->
  <%= link_to 'Support', new_support_ticket_path, class: 'nav-link text-white' %>
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2021 Copyright:
    <%# <a class="text-white" href="https://mdbootstrap.com/">mmm.com</a> %>
    <%= link_to 'www.mmm.com', root_path, class: 'text-white' %>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_header.html.erb
<header class="header-area header-sticky">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <nav class="main-nav">
          <!-- ***** Logo Start ***** -->
          <a href="<%= root_path %>" class="logo">
            <%# <img src="assets/images/logoTwo.png" alt="EduWell Template"> %>
            <%= image_tag asset_path('template/logoTwo.png', alt: '') %>
          </a>
          <!-- ***** Logo End ***** -->
          <!-- ***** Menu Start ***** -->
          <ul class="nav">
            <li class="scroll-to-section"><%= link_to 'Home', root_path, class: 'nav-link active' %></li>
            <% unless user_signed_in? %>
              <li class="scroll-to-section"><%= link_to 'SignIn', new_user_session_path, class: "nav-link" %></li>
              <li class="scroll-to-section"><%= link_to 'SignUp', new_user_registration_path, class: "nav-link" %></li>
            <% else %>
              <li class="scroll-to-section"><%= link_to 'Dashboard', users_dashboard_path, class: "nav-link" %></li>
              <li class="has-sub">
              <a href="javascript:void(0)">Pay in/out Detail</a>
              <ul class="sub-menu">
                <li><%= link_to 'Growth', show_growth_pay_ins_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'History', payment_history_path, class: 'dropdown-item' %></li>
              </ul>
              </li>
              <li class="has-sub">
              <a href="javascript:void(0)">Participants</a>
              <ul class="sub-menu">
                <li><%= link_to 'Referrals', users_path(filtered_with: 'referrals'), class: 'dropdown-item' %></li>
                <li><%= link_to 'Participants', users_path(filtered_with: 'participants'), class: 'dropdown-item' %></li>
              </ul>
              </li>
              <li class="has-sub">
              <a href="javascript:void(0)">Account</a>
              <ul class="sub-menu">
                <li><%= link_to 'Accounts', accounts_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'Wallets', wallets_path, class: 'dropdown-item' %></li>
              </ul>
              </li>
              <li class="has-sub">
              <a href="javascript:void(0)"><%= "#{current_user.name}(#{current_user.role})" %></a>
              <ul class="sub-menu">
                <li data-keepOpenOnClick><span class='text-bold'>Referral link:</span> <span id='myReferralId' class='fw-lighter'><%= new_user_registration_url(invited_by: referal_id(current_user)) %></span></li>
                <li><%= link_to 'Profile', edit_user_registration_path, class: "nav-link" %></li>
                <li><%= link_to 'Logout', destroy_user_session_path, method: 'delete', class: "nav-link" %></li>
              </ul>
              </li>
            <% end %>
          </ul>
          <a class='menu-trigger'>
            <span>Menu</span>
          </a>
          <!-- ***** Menu End ***** -->
        </nav>
      </div>
    </div>
  </div>
  <div id='googleTranslater' class='float-end'></div>
</header>

<script>
  $(document).ready(function() {
    //according to loftblog tut
    $('.nav li:first').addClass('active');

    // var showSection = function showSection(section, isAnimate) {
    //   var
    //     direction = section.replace(/#/, ''),
    //     reqSection = $('.section').filter('[data-section="' + direction + '"]'),
    //     reqSectionPos = reqSection.offset().top - 0;

    //   if (isAnimate) {
    //     $('body, html').animate({
    //         scrollTop: reqSectionPos
    //       },
    //       800);
    //   } else {
    //     $('body, html').scrollTop(reqSectionPos);
    //   }

    // };

    var checkSection = function checkSection() {
      $('.section').each(function() {
        var
          $this = $(this),
          topEdge = $this.offset().top - 80,
          bottomEdge = topEdge + $this.height(),
          wScroll = $(window).scrollTop();
        if (topEdge < wScroll && bottomEdge > wScroll) {
          var
            currentId = $this.data('section'),
            reqLink = $('a').filter('[href*=\\#' + currentId + ']');
          reqLink.closest('li').addClass('active').
          siblings().removeClass('active');
        }
      });
    };

    // $('.main-menu, .responsive-menu, .scroll-to-section').on('click', 'a', function(e) {
    //   e.preventDefault();
    //   showSection($(this).attr('href'), true);
    // });

    $(window).scroll(function() {
      checkSection();
    });
  })
</script>

app/views/shared/_pay_in_payment_modal.html.erb
<div class="modal show" id="payInPaymentModal-<%=payment.id%>" tabindex="-1" aria-labelledby="payInPaymentModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="payInPaymentModalLabel">Pay In Payment</h5>
      </div>
      <div class="modal-body">
        To wallet: <span id='payInAmtwalletNumberToCopy'><%= payment.receiver_wallet_number.strip %></span>
        <span class="clipboard-btn btn btn-sm btn-primary" data-clipboard-action="copy" data-clipboard-target="#payInAmtwalletNumberToCopy">copy</span>
        <p>Pay In Amount: <%= payment.amount %></p>
      </div>

      <%= render partial: 'shared/payment_verification_form', locals: {payment: payment} %>
    </div>
  </div>
</div>

app/views/shared/_payment_verification_form.html.erb
<%= form_for payment, url: verify_payment_path(payment_id: payment.id), remote: true do |f| %>
  <div class="card">
    <div class="card-body">
      <label for="transaction_id" class="form-label">Transaction Hash: </label>
      <%= f.text_field :transaction_id, required: true, class: 'form-control' %>
    </div>
  </div>
  <div class="modal-footer">
    <span id='paymentNotConfirmedError' class='error text-danger'></span>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= f.submit :Confirm, class: "btn btn-success" %>
  </div>
<% end %>